version: '2'
services:
  web:
    build:
      context: ./dockerfile-wordpress
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - wp_web:/var/www/localhost/htdocs
      - ./wp-content:/var/www/localhost/htdocs/wp-content
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - wp_data:/var/lib/mysql
volumes:
  wp_web:
  wp_data:
